list: $/awme/stockist/models/category/columns.yaml
modelClass: AWME\Stockist\Models\Category
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
# Records to display per page
recordsPerPage: 25
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'awme/stockist/categories/update/:id'
