plugin:
    name: Stockist
    description: 'Herramienta de control de Stock y Ventas para comercios.'
    author: 'LucasZdv, Awebsome'
    icon: oc-icon-shopping-cart
    homepage: 'http://awebsome.me'
navigation:
    stockist:
        label: 'awme.stockist::lang.plugin.name'
        url: awme/stockist/sales
        icon: icon-cubes
        permissions:
            - awme.stockist.usage
        sideMenu:
            stockist-tills:
                label: 'awme.stockist::lang.tills.menu_label'
                url: awme/stockist/tills
                icon: icon-usd
                permissions:
                    - awme.stockist.read_tills
            stockist-sales:
                label: 'awme.stockist::lang.sales.menu_label'
                url: awme/stockist/sales
                icon: icon-cart-plus
                permissions:
                    - awme.stockist.read_sales
            stockist-paymethods:
                label: 'awme.stockist::lang.paymethods.menu_label'
                url: awme/stockist/paymethods
                icon: icon-credit-card
                permissions:
                    - awme.stockist.read_paymethods
            stockist-products:
                label: Products
                url: awme/stockist/products
                icon: icon-cubes
                permissions:
                    - awme.stockist.read_products
            stockist-categories:
                label: 'awme.stockist::lang.categories.menu_label'
                url: awme/stockist/categories
                icon: icon-folder-open
                permissions:
                    - awme.stockist.read_categories
permissions:
    awme.stockist.settings:
        tab: 'awme.stockist::lang.plugin.name'
        label: 'Stockist Settings'
    awme.stockist.usage:
        tab: 'awme.stockist::lang.plugin.name'
        label: 'awme.stockist::lang.permission.usage'
    awme.stockist.read_tills:
        tab: 'awme.stockist::lang.plugin.name'
        label: 'awme.stockist::lang.permission.read_tills'
    awme.stockist.read_sales:
        tab: 'awme.stockist::lang.plugin.name'
        label: 'awme.stockist::lang.permission.read_sales'
    awme.stockist.read_paymethods:
        tab: 'awme.stockist::lang.plugin.name'
        label: 'awme.stockist::lang.permission.read_paymethods'
    awme.stockist.read_products:
        tab: 'awme.stockist::lang.plugin.name'
        label: 'awme.stockist::lang.permission.read_products'
    awme.stockist.read_categories:
        tab: 'awme.stockist::lang.plugin.name'
        label: 'awme.stockist::lang.permission.read_categories'
