title: PayMethods
modelClass: AWME\Stockist\Models\PayMethod
list: $/awme/stockist/models/paymethod/columns.yaml
recordUrl: 'awme/stockist/paymethods/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
