list: $/awme/stockist/models/till/columns.yaml
modelClass: AWME\Stockist\Models\Till
title: Tills
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: false
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'awme/stockist/tills/update/:id'
