# ===================================
#  Relation Behavior Config
# ===================================
products_pivot_model:
    label: awme.stockist::lang.sales.products
    view:
        list: ~/plugins/awme/stockist/models/saleproductpivot/columns.yaml
        toolbarButtons: add|remove
        showSearch: true
    manage:
        list: ~/plugins/awme/stockist/models/product/columns.yaml
        showSearch: true
    pivot:
        form: ~/plugins/awme/stockist/models/saleproductpivot/fields.yaml