list: $/awme/stockist/models/sale/columns.yaml
modelClass: AWME\Stockist\Models\Sale
title: awme.stockist::lang.sales.sales
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: false
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'awme/stockist/sales/update/:id'
# Records to display per page
recordsPerPage: 30
# Default sorting column
defaultSort:
    column: updated_at
    direction: desc

# Filter widget configuration
filter: config_filter.yaml